// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjbfXQ-iYTUtupyC6N6yNYH63526oKVUE',
    appId: '1:252961405039:web:4b49f08c8f9ed8d68f359a',
    messagingSenderId: '252961405039',
    projectId: 'skillboost-d2b56',
    authDomain: 'skillboost-d2b56.firebaseapp.com',
    storageBucket: 'skillboost-d2b56.firebasestorage.app',
    measurementId: 'G-1ZQG3B5K7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZf00rh9K7OLTSjPxbJMfquzMLYfwCBsk',
    appId: '1:252961405039:android:09524dd7b977d0998f359a',
    messagingSenderId: '252961405039',
    projectId: 'skillboost-d2b56',
    storageBucket: 'skillboost-d2b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjFN4h2AiU7oBz_wv_7kWOIYvy6bDHJ90',
    appId: '1:252961405039:ios:e43d64cc28227e668f359a',
    messagingSenderId: '252961405039',
    projectId: 'skillboost-d2b56',
    storageBucket: 'skillboost-d2b56.firebasestorage.app',
    iosBundleId: 'com.example.skillboost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjFN4h2AiU7oBz_wv_7kWOIYvy6bDHJ90',
    appId: '1:252961405039:ios:e43d64cc28227e668f359a',
    messagingSenderId: '252961405039',
    projectId: 'skillboost-d2b56',
    storageBucket: 'skillboost-d2b56.firebasestorage.app',
    iosBundleId: 'com.example.skillboost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjbfXQ-iYTUtupyC6N6yNYH63526oKVUE',
    appId: '1:252961405039:web:9821f951d65219a78f359a',
    messagingSenderId: '252961405039',
    projectId: 'skillboost-d2b56',
    authDomain: 'skillboost-d2b56.firebaseapp.com',
    storageBucket: 'skillboost-d2b56.firebasestorage.app',
    measurementId: 'G-BMB4JFDNPR',
  );
}
